# Generated by Django 6.0.6 on 2026-07-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Filme', 'Filme'), ('Séries', 'Série')], max_length=10)),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
